### ISSUE TITLE
Survey (Not A Legit Issue) 

### ISSUE THREAD

**Issue by AarinDave** [kethan1/Level-3-Evaluation#1]
Hello, Kethan. How have you been doing today? I know this is obviously the wrong place to put this, but I wanted to survey you for one PyPI module I am currently making. I added this here because I think this is the easiest place to ask you.

As you are past Level 3, I wanted to ask this question.

If you were to ask Python to add functions you desperately needed, what would they be? If you don't understand the question, I will rephrase it. What functions do you wish could be added in built-in Python but it doesn't exist in other notable modules? One example could be a function to sort dictionaries by either its key or value.

Thanks for reading and responding. I hope you have a great day!

**Comment by kethan1** [comment]
I'm actually in Level 5 currently :). I finished Level 4, then took the evaluation for Level 3. 

Hmm. True constants would be nice (pretty much variables that you couldn't change once you defined them, similar to `const` in Javascript). I'll get back to you when I think of more.

**Comment by kethan1** [comment]
Making Python (CPython) faster would be nice, though don't know how feasible this is.

**Comment by AarinDave** [comment]
Thanks for your response! I am sure you will think of more, so you may reply to this comment when you do. Overall though, thank you for your response! Have a great day!

**Comment by AarinDave** [comment]
If you don't mind, Kethan, could you delete the issue?
